config/routes.rb
Rails.application.routes.draw do


get '/admin', to: 'admin#index', as: 'admins'

get '/admin/:id', to: 'admin#show', as: 'admin'

get '/admin/:article_id/comments/:id/edit', to: 'comments#edit', as: "edit_admin_comment"

get '/informations/a-propos', to: 'informations#a_propos', as: 'informations_a_propos'
get '/informations/cgu', to: 'informations#cgu', as: 'informations_cgu'

get 'articles/search', to: 'articles#search', as: 'articles_search'

get '/changelanguage', to: 'application#changelanguage', as: 'change_language'


get 'connexion', to: 'admin#connexion', as: 'connexion'
post 'connexion', to: 'admin#connexion', as: 'connexion_post'
post 'inscription', to: 'admin#create', as: 'inscription_post'
get 'inscription', to: 'admin#inscription', as: 'inscription_get'

  get 'rails/generate'

  get 'rails/controller'

  get 'rails/articles'

  get 'rails/admin'

  resources :contacts
  get 'welcome/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html




  resources :articles do
    resources :comments
  end

  root 'welcome#index'

end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
            length: { minimum: 5 }

  scope :by_updated_at, -> { order(updated_at: :desc) }
  scope :online, -> (online) { where(online: online) }


end

app/controllers/articles_controller.rb
  class ArticlesController < ApplicationController

    http_basic_authenticate_with name: "user", password: "password", except: [:index, :show, :search]

    #before_action do |variable|
    #    puts 'Je suis le Before !!!'
    #end
    before_action :set_article, only: [:edit, :update, :show, :destroy]

    after_action do |variable|
        puts 'Je suis le After !!!'
    end

    around_action :around
    def around
        puts "Before !!!"
        yield
        puts "After !!!"
    end

    def new
      @article = Article.new
    end

    def index
      #session[:user] = {id: '123', username: 'Regit05'}
      @articles = Article.online(true).by_updated_at.all

    end

    def show
      #@article = Article.find(params[:id])
      #@session = session[:user]
      @comments = @article.comments.all
    end

    def edit
      #@article = Article.find(params[:id])
    end

    def update
      #@article = Article.find(params[:id])

      if @article.update(article_params)
        flash[:success] = "Post modifié avec succés"
        redirect_to admin_path(@article)
      else
        flash[:danger] = "Le post n'a pas pu être modifié"
        redirect_to edit_article_path(@article)
      end
    end

    def destroy
      #@article = Article.find(params[:id])
      @article.destroy

      redirect_to admins_path
    end

    def create
      #render plain: params[:article].inspect

      #@article = Article.new(params.require(:article).permit(:title,:text))
      @article = Article.new(article_params)
      #@article.save
      #redirect_to @article

      if @article.save
        redirect_to admin_path(@article)
      else
        render 'new'
      end
    end

    def search
        #render plain: params[:search].inspect
        @articles = Article.online(true).where(Article.arel_table[:title].matches("%#{params[:search]}%")).by_updated_at
        #.paginate(page: params[:page], per_page: 3)
    end


    private
      def article_params
        params.require(:article).permit(:title,:text,:image_url)
      end

      def set_article
        @article = Article.find(params[:id])
      end
  end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>

    <% if @article.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@article.errors.count, "error") %> prohibited
            this article from being saved:
          </h2>
          <ul>
            <% @article.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </p>

    <p>
      <%= form.label :text %><br>
      <%= form.text_area :text %>
    </p>

    <p>
      <%= form.label :image_url %><br>
      <%= form.text_field :image_url %>
    </p>

    <p>
      <%= form.submit %>
    </p>

<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<div class="container">
    <% if session[:danger] %>
        <div class="alert alert-success"><%= flash[:danger] %></div>
    <% end %>
    <%= yield %>
</div>

<%= render 'form' %>

<%= link_to 'back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing Article</h1>

<%= link_to 'Rechercher un article', articles_search_path %>
<%= form_tag articles_search_path, :method => 'get', class: '' do %>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search" %>
<% end %>

<table>
  <% @articles.each do |article| %>
    <tr>
      <td><p><%= article.created_at %></p><p><%= article.updated_at %></p>
      <td><p><%= article.title %> <%= article.created_at %> <%= article.updated_at %></p>
      <img height="100px" src="<%= article.image_url %>"></td>
      <td><%= link_to 'show', article_path(article) %></td>
  <% end %>

</table>

app/views/articles/new.html.erb
<h1>Articles</h1>

<%= render 'form' %>

<%= link_to 'back', articles_path %>

app/views/articles/search.html.erb
<h1>Searching Article</h1>

<%= form_tag articles_search_path, :method => 'get', class: '' do %>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search" %>
<% end %>

<table>
  <% @articles.each do |article| %>
    <tr>
      <td><p><%= article.created_at %></p><p><%= article.updated_at %></p>
      <td><p><%= article.title %> <%= article.created_at %> <%= article.updated_at %></p>
      <img height="100px" src="<%= article.image_url %>"></td>
      <td><%= link_to 'show', article_path(article) %></td>
  <% end %>

</table>

app/views/articles/show.html.erb
<img width="400px" src="<%= @article.image_url %>">

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<h2>Comments</h2>
<%= render 'comments/show' %>

<h2>Add a comment:</h2>
<%= render 'comments/form_new' %>

<%= link_to 'Back', articles_path %>