config/routes.rb
Rails.application.routes.draw do


get '/admin', to: 'admin#index', as: 'admins'

get '/admin/:id', to: 'admin#show', as: 'admin'

get '/admin/:article_id/comments/:id/edit', to: 'comments#edit', as: "edit_admin_comment"

get '/informations/a-propos', to: 'informations#a_propos', as: 'informations_a_propos'
get '/informations/cgu', to: 'informations#cgu', as: 'informations_cgu'

get 'articles/search', to: 'articles#search', as: 'articles_search'

get '/changelanguage', to: 'application#changelanguage', as: 'change_language'


get 'connexion', to: 'admin#connexion', as: 'connexion'
post 'connexion', to: 'admin#connexion', as: 'connexion_post'
post 'inscription', to: 'admin#create', as: 'inscription_post'
get 'inscription', to: 'admin#inscription', as: 'inscription_get'

  get 'rails/generate'

  get 'rails/controller'

  get 'rails/articles'

  get 'rails/admin'

  resources :contacts
  get 'welcome/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html




  resources :articles do
    resources :comments
  end

  root 'welcome#index'

end

app/views/admin/_formadmin.html.erb
<%= form_with model: @admin, local: true do |formadmin| %>
    <p>
      <%= formadmin.label :email %><br>
      <%= formadmin.email_field :email %>
    </p>

    <p>
      <%= formadmin.label :password %><br>
      <%= formadmin.password_field :password %>
    </p>

    <p>
      <%= formadmin.submit %>
    </p>

<% end %>

app/views/admin/_formconnexion.html.erb
<%= form_with model: @admin, local: true do |form| %>
    <p>
      <%= form.label :email %><br>
      <%= form.email_field :email %>
    </p>

    <p>
      <%= form.label :password %><br>
      <%= form.password_field :password %>
    </p>

    <p>
      <%= form.submit value:"Me connecter" %>
    </p>

<% end %>

app/views/admin/connexion.html.erb
CONNEXION

<% @admins.each do |admin| %>
    <tr>
      <td><%= admin.email %></td>
      <td><%= admin.password %></td>
    </tr>
<% end %>

<%= render 'formconnexion' %>

<%= link_to 'Inscription', inscription_get_path%>

app/views/admin/index.html.erb
<%= link_to 'New Article', new_article_path %>
<%= link_to 'Contacts', contacts_path %>

<h1>Listing Article</h1>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="3"></th>
  </tr>

  <% @admins.each do |admin| %>
    <tr>
      <td><%= admin.title %></td>
      <td><%= admin.text %></td>
      <td><button class="btn" ><%= link_to 'show', admin_path(admin)%></button></td>
      <td><button class="btn" ><%= link_to 'edit', edit_article_path(admin) %></button></td>
      <td><button class="btn" ><%= link_to 'Destroy', article_path(admin), method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
    </tr>
  <% end %>

</table>

app/views/admin/inscription.html.erb
<h1>Inscription</h1>

<%= render 'formadmin' %>

<%= link_to 'back', connexion_path %>

app/views/admin/show.html.erb
<div class="container">
    <% if flash[:success] %>
        <div class="alert alert-success"><%= flash[:success] %></div>
    <% end %>
    <%= yield %>
</div>




<img width="400px" src="<%= @admin.image_url %>">

<p>
  <strong>Title:</strong>
  <%= @admin.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @admin.text %>
</p>

<h2>Comments</h2>
<%= render @admin.comments %>


<%= link_to 'Edit', edit_article_path(@admin) %> |
<%= link_to 'Back', admins_path %>