config/routes.rb
Rails.application.routes.draw do


get '/admin', to: 'admin#index', as: 'admins'

get '/admin/:id', to: 'admin#show', as: 'admin'

get '/admin/:article_id/comments/:id/edit', to: 'comments#edit', as: "edit_admin_comment"

get '/informations/a-propos', to: 'informations#a_propos', as: 'informations_a_propos'
get '/informations/cgu', to: 'informations#cgu', as: 'informations_cgu'

get 'articles/search', to: 'articles#search', as: 'articles_search'

get '/changelanguage', to: 'application#changelanguage', as: 'change_language'


get 'connexion', to: 'admin#connexion', as: 'connexion'
post 'connexion', to: 'admin#connexion', as: 'connexion_post'
post 'inscription', to: 'admin#create', as: 'inscription_post'
get 'inscription', to: 'admin#inscription', as: 'inscription_get'

  get 'rails/generate'

  get 'rails/controller'

  get 'rails/articles'

  get 'rails/admin'

  resources :contacts
  get 'welcome/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html




  resources :articles do
    resources :comments
  end

  root 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
        <%= yield %>
    </div>

    <div>
        <%= link_to 'A propos', informations_a_propos_path %> |
        <%= link_to 'CGU', informations_cgu_path %> |

        <div class="container" id="lang">
            <% if cookies[:language] %>
                <%= cookies[:language] %>
            <% end %>
        </div>
        <div id="langchange" >
            <%= link_to "FR", change_language_path(:langue => "FR") %>
            <%= link_to "EN", change_language_path(:langue => "EN") %>
        </div>
    </div>
  </body>

</html>